
project_id = "tedjuorbafahlnplndye"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
# This is the correct format according to the error message
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

[analytics]
enabled = false
port = 54327
vector_port = 54328
gcp_project_id = ""
gcp_project_number = ""
gcp_jwt_path = "supabase/gcloud.json"

# Fix function configuration format
# Instead of having 'max_retries' which is invalid, remove it
[functions.update-user-password]
verify_jwt = true

[functions.delete-employee]
verify_jwt = true
