// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tedjuorbafahlnplndye.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRlZGp1b3JiYWZhaGxucGxuZHllIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NTMzMzIsImV4cCI6MjA1MjUyOTMzMn0.E2MGml0yB8CzI8tCs5EEwl96NDcY9KrpKFTQ_sqfs-8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);